"""remove created_at atribute

Revision ID: 260ae8caff39
Revises: f62b55373cf3
Create Date: 2023-09-20 20:07:08.436088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260ae8caff39'
down_revision = 'f62b55373cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
